Fix firebase testing
Firebase testing portion failed because the gradle build didn't
generate the `app-internal-debug.apk` file.

  ERROR: (gcloud.firebase.test.android.run)
  [./app/build/outputs/apk/internal/debug/app-internal-debug.apk] not found or not accessible

the target `gradlew :app:assembleInternalDebugAndroidTest` doesn't
generate that file but `gradlew assembleInternalDebug` does.